server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loans/**

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
